### ISSUE TITLE
Dependency on internal AGP API breaks on AGP 3.4

### ISSUE THREAD

**Issue by hzsweers** [bugsnag/bugsnag-android-gradle-plugin#134]
Tested updating to AGP 3.4.0-alpha01 today in https://github.com/hzsweers/catchup

Happens on configuration

```
Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/internal/core/Toolchain
        at com.bugsnag.android.gradle.BugsnagPlugin.getCmakeToolchain(BugsnagPlugin.groovy:352)
        at com.bugsnag.android.gradle.BugsnagPlugin.setupNdkMappingFileUpload(BugsnagPlugin.groovy:149)
        at com.bugsnag.android.gradle.BugsnagPlugin$_applyBugsnagToVariant_closure8.doCall(BugsnagPlugin.groovy:125)
        at com.bugsnag.android.gradle.BugsnagPlugin.applyBugsnagToVariant(BugsnagPlugin.groovy:117)
        at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:579)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:506)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:78)
        at com.bugsnag.android.gradle.BugsnagPlugin$_apply_closure1$_closure15.doCall(BugsnagPlugin.groovy:52)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:186)
        at org.gradle.api.DomainObjectCollection$all$0.call(Unknown Source)
        at com.bugsnag.android.gradle.BugsnagPlugin$_apply_closure1.doCall(BugsnagPlugin.groovy:51)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1$1.run(DefaultListenerBuildOperationDecorator.java:186)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.run(DefaultListenerBuildOperationDecorator.java:181)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure.doCall(DefaultListenerBuildOperationDecorator.java:178)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatc
```

**Comment by fractalwrench** [comment]
Thanks for letting us know about this @hzsweers - we'll start investigating a fix for this.
