### ISSUE TITLE
Incompatible with Gradle 7.0

### ISSUE THREAD

**Issue by ZacSweers** [bugsnag/bugsnag-android-gradle-plugin#369]
### Describe the bug
The gradle plugin uses/depends on a groovy API that is no longer present in Gradle 7.0

### Steps to reproduce
Update to Gradle 7.0-milestone-2

Observe this trace when manifest parsing happens:

```
Caused by: java.lang.NoSuchMethodError: groovy.xml.Namespace.get(Ljava/lang/String;)Lgroovy/xml/QName;
        at com.bugsnag.android.gradle.AndroidManifestParser.getManifestMetaData(AndroidManifestParser.kt:123)
        at com.bugsnag.android.gradle.AndroidManifestParser.hasBuildUuid(AndroidManifestParser.kt:118)
        at com.bugsnag.android.gradle.AndroidManifestParser.writeBuildUuid(AndroidManifestParser.kt:91)
        at com.bugsnag.android.gradle.BugsnagManifestUuidTaskV2.updateManifest(BugsnagManifestUuidTaskV2.kt:51)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:498)
```

### Environment
* Android Studio version: N/A
* Android Gradle version: N/A
* Bugsnag manifest section (if modified): N/A

**Comment by yousif-bugsnag** [comment]
Hey @ZacSweers, thanks for the report! We'll look into fixing this in a future release.

**Comment by yogurtearl** [comment]
Still happens with [Gradle 7 RC1](https://docs.gradle.org/7.0-rc-1/userguide/upgrading_version_6.html#changes_to_groovy_and_groovy_dsl)

Possibly related to the upgrade to Groovy 3 -> 
https://docs.gradle.org/7.0-rc-1/userguide/upgrading_version_6.html#changes_to_groovy_and_groovy_dsl

**Comment by ZacSweers** [comment]
Namespace is ins groovy-xml, which they do say is included 🤔

**Comment by kylannjohnson** [comment]
If you upgrade the project to Gradle 7, you get Groovy 3.0.7.  That version contains `groovy.xml.Namespace`, but that class returns `groovy.namespace.QName` rather than `groovy.xml.QName` (from version `1.3-2.5.12`).

However, if you upgrade this project to Gradle 7, then the `com.bmuschko.nexus` plugin can't be applied because it's still using using Gradle 6 and also MavenPlugin (which is deprecated in Gradle 7)

A possible solution would be to create an alternate version of Namespace that uses reflection to return the correct QName instance.  I got all the tests to pass (by running`gw test`) by returning calling `getQualifiedName()` as the `toString()` via reflection.  

 I totally concede that this is a brittle approach, but it seems to work for now until we can move this project to Gradle 7.

**Comment by xander-jones** [comment]
Now compatible with Gradle 7.0 as of https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v5.7.6 🎉
