### ISSUE TITLE
Ignore SSL Handshake on Upload

### ISSUE THREAD

**Issue by chrjsorg** [bugsnag/bugsnag-android-gradle-plugin#370]
Hello,

we're currently (finally) upgrading the gradle and other top-level dependencies of our application.

- Gradle: 5.6.4 -> 6.5
- Build Tools 3.6.3 -> 4.1.2
- Bugsnag Gradle Plugin 3.6.0 -> 5.7.4 / 4.7.5

With these changes we are currently not able to upload mapping files to our on-premise bugsnag instance because of a SSL handshake issue.

```
Caused by: java.lang.IllegalStateException: Bugsnag request failed to complete
        at com.bugsnag.android.gradle.internal.BugsnagHttpClientHelperKt.runRequestWithRetries(BugsnagHttpClientHelper.kt:118)
...
        at com.bugsnag.android.gradle.internal.UploadRequestClient.makeRequestIfNeeded(UploadRequestClient.kt:38)
        ... 97 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
....
        at com.bugsnag.android.gradle.BugsnagMultiPartUploadRequest.uploadToServer(BugsnagMultiPartUploadRequest.kt:58)
        at com.bugsnag.android.gradle.BugsnagMultiPartUploadRequest.access$uploadToServer(BugsnagMultiPartUploadRequest.kt:23)
        at com.bugsnag.android.gradle.BugsnagMultiPartUploadRequest$uploadMultipartEntity$1.invoke(BugsnagMultiPartUploadRequest.kt:41)
        at com.bugsnag.android.gradle.BugsnagMultiPartUploadRequest$uploadMultipartEntity$1.invoke(BugsnagMultiPartUploadRequest.kt:23)
        at com.bugsnag.android.gradle.internal.BugsnagHttpClientHelperKt.runRequestWithRetries(BugsnagHttpClientHelper.kt:112)
```

The certificate on the endpoint should be fine. It also doesn't work with version 4.7.5. I thought it might be related to the okhttp changes with 5.0, but now. 4.7.5 also doesn't work. 

We currently have no idea how to fix this.

Is it possible to "ignore ssl stuff" on executing the task? Thank you.

**Comment by johnkiely1** [comment]
Hi @chrjsorg,

Would you be able to send us some screenshots/code snippets from your Bugsnag Gradle plugin configuration code in your `build.gradle` files. You can do that via support@bugsnag.com if you don't want to share that here.  

It does look like this could be a okhttp related problem, possibly a dependency conflict pulling in an incompatible version of okhttp. Do you have any other dependencies that require different versions of okhttp. You could run your build with `--scan` parameter to see the full dependency tree and which versions have been used. 

Is this the complete stacktrace or is there any more to it? Perhaps you could try running the build with` --stacktrace --debug` to see if it would give a more complete trace.

If you could also send us the output of either/both of the above that would also be helpful, thanks.

**Comment by chrjsorg** [comment]
I just sent you an email, thank you.

**Comment by chrjsorg** [comment]
Thanks for the great support.

**Comment by chrjsorg** [comment]
I fixed the issue btw:
I installed a current version of openjdk and the build & upload works again. 

`brew install adoptopenjdk`
-> 
```
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```
