### ISSUE TITLE
AGP 7 incompatibilities

### ISSUE THREAD

**Issue by ZacSweers** [bugsnag/bugsnag-android-gradle-plugin#382]
Figured I would start a tracker for collecting AGP 7 incompatibilities, which contains some breaking changes

**Comment by ZacSweers** [comment]
`ArtifactType.MERGED_MANIFEST` has now moved to `SingleArtifact.MERGED_MANIFEST`

```
Caused by: java.lang.NoClassDefFoundError: com/android/build/api/artifact/ArtifactType$MERGED_MANIFEST
	at com.bugsnag.android.gradle.internal.ManifestUuidTaskV2CompatKt.wireManifestUpdaterTask(ManifestUuidTaskV2Compat.kt:112)
	at com.bugsnag.android.gradle.internal.ManifestUuidTaskV2CompatKt$registerUuidTaskAGP42$1.invoke(ManifestUuidTaskV2Compat.kt:47)
	at com.bugsnag.android.gradle.internal.ManifestUuidTaskV2CompatKt$registerUuidTaskAGP42$1.invoke(ManifestUuidTaskV2Compat.kt)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtensionImpl.kt:52)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtensionImpl.kt:51)
	at com.android.build.api.extension.impl.OperationsRegistrar.executeOperations(OperationsRegistrar.kt:58)
	at com.android.build.gradle.internal.VariantManager.createVariantsFromCombination(VariantManager.kt:944)
	at com.android.build.gradle.internal.VariantManager.computeVariants(VariantManager.kt:210)
	at com.android.build.gradle.internal.VariantManager.createVariants(VariantManager.kt:160)
	at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.java:720)
	at com.android.build.gradle.internal.profile.NoOpAnalyticsConfiguratorService.recordBlock(NoOpAnalyticsConfiguratorService.kt:48)
	at com.android.build.gradle.internal.plugins.BasePlugin.lambda$createTasks$13(BasePlugin.java:627)
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:35)
	at 
```

**Comment by johnkiely1** [comment]
Hey @ZacSweers, 

As you may already be aware we are looking to support AGP 7 in the future, we don't have a timeframe as yet but this will come in really useful. Thanks for starting this.

**Comment by rovkinmax** [comment]
This bug blocks using bugsnag with Jetpack Compose :(

**Comment by ZacSweers** [comment]
You could offer to PR a solution?

**Comment by johnkiely1** [comment]
Hey @ZacSweers, @rovkinmax 

We've now released [v7.0.0-beta01](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v7.0.0-beta01) of the plugin which offers AGP7 Support and solves the above error.
There is an upgrade guide available [here](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/v7.0.0-beta01/UPGRADING.md).
Do bear in mind this is currently a beta as AGP7 is still in beta.  

Closing this issue for now but happy to reopen if further issues arise.

**Comment by ZacSweers** [comment]
@johnkiely1 any update now that AGP 7 stable is released?

**Comment by mattdyoung** [comment]
Hi @ZacSweers 

Yes, we'll be looking to release a non-beta v7.x version of bugsnag-android-gradle-plugin soon. We believe [v7.0.0-beta01](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v7.0.0-beta01) will continue to work with AGP 7.0.0 for now but are planning some further testing as part of the formal release.
