### ISSUE TITLE
Unable to load class 'com.android.build.api.artifact.ArtifactType$MERGED_MANIFEST'

### ISSUE THREAD

**Issue by lawgimenez** [bugsnag/bugsnag-android-gradle-plugin#399]
### Describe the bug
Upgrade to latest Gradle 7.1

### Steps to reproduce
1. Build project

### Environment
* Android Studio version: Arctic Fox 2020.3.1 Beta 3
* Android Gradle version: 7.1
* Bugsnag manifest section (if modified):

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
Caused by: java.lang.NoClassDefFoundError: com/android/build/api/artifact/ArtifactType$MERGED_MANIFEST
	at com.bugsnag.android.gradle.internal.ManifestUuidTaskV2CompatKt.wireManifestUpdaterTask(ManifestUuidTaskV2Compat.kt:112)
	at com.bugsnag.android.gradle.internal.ManifestUuidTaskV2CompatKt$registerUuidTaskAGP42$1.invoke(ManifestUuidTaskV2Compat.kt:47)
	at com.bugsnag.android.gradle.internal.ManifestUuidTaskV2CompatKt$registerUuidTaskAGP42$1.invoke(ManifestUuidTaskV2Compat.kt)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtensionImpl.kt:69)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$onVariants$1.execute(AndroidComponentsExtensionImpl.kt:68)
	at com.android.build.api.extension.impl.OperationsRegistrar.executeOperations(OperationsRegistrar.kt:58)
	at com.android.build.gradle.internal.VariantManager.createVariantsFromCombination(VariantManager.kt:983)
	at com.android.build.gradle.internal.VariantManager.computeVariants(VariantManager.kt:223)
	at com.android.build.gradle.internal.VariantManager.createVariants(VariantManager.kt:169)
	at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.java:765)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:69)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:54)
	at com.android.build.gradle.internal.profile.AnalyticsResourceManager.recordBlockAtConfiguration(AnalyticsResourceManager.kt:207)
	at com.android.build.gradle.internal.profile.AnalyticsConfiguratorService.recordBlock(AnalyticsConfiguratorService.kt:85)
	at com.android.build.gradle.internal.plugins.BasePlugin.lambda$createTasks$13(BasePlugin.java:653)
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
	at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:35)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:112)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)

```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by johnkiely1** [comment]
Hi @lawgimenez. 

We are aware of this error and will be occurring as a direct result of using AGP 7 as the class has been moved. We currently don't support AGP 7 but we are working on adding that. I will update here once that work has been completed.

In the meantime the only known workaround would be to downgrade to an earlier version of AGP.
