### ISSUE TITLE
Cannot get property 'splitsInfo' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by hzsweers** [bugsnag/bugsnag-android-gradle-plugin#59]
Getting this with the latest beta on AGP 3.0, seems related to the recent apk splits work?

```
Caused by: groovy.lang.MissingPropertyException: Cannot get property 'splitsInfo' on extra properties extension as it does not exist
        at org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.getProperty(DefaultExtraPropertiesExtension.java:56)
        at com.bugsnag.android.gradle.BugsnagVariantOutputTask.getManifestPath(BugsnagVariantOutputTask.groovy:37)
        at com.bugsnag.android.gradle.BugsnagManifestTask_Decorated.getManifestPath(Unknown Source)
        at com.bugsnag.android.gradle.BugsnagManifestTask_Decorated$getManifestPath.callCurrent(Unknown Source)
        at com.bugsnag.android.gradle.BugsnagManifestTask.updateManifest(BugsnagManifestTask.groovy:24)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

**Comment by kattrali** [comment]
Thanks for the report @hzsweers. Which beta/RC of AGP are you using?

**Comment by hzsweers** [comment]
rc1

**Comment by fractalwrench** [comment]
This can be reproduced by invoking `./gradlew build` on the example project, rather than `./gradlew clean build`.
