### ISSUE TITLE
upload failing due to exception relating to versionCode cast

### ISSUE THREAD

**Issue by ellsworthrw** [bugsnag/bugsnag-android-gradle-plugin#78]
### Expected behavior
upload mapping file

### Observed behavior
exception thrown
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '50800000' with class 'java.lang.String' to class 'java.lang.Integer'
        at com.bugsnag.android.gradle.BugsnagVariantOutputTask.getVersionCode(BugsnagVariantOutputTask.groovy:172)
        at com.bugsnag.android.gradle.BugsnagVariantOutputTask$getVersionCode$0.callCurrent(Unknown Source)
        at com.bugsnag.android.gradle.BugsnagVariantOutputTask.readManifestFile(BugsnagVariantOutputTask.groovy:128)
        at com.bugsnag.android.gradle.BugsnagUploadProguardTask.super$4$readManifestFile(BugsnagUploadProguardTask.groovy)
        at com.bugsnag.android.gradle.BugsnagUploadProguardTask.upload(BugsnagUploadProguardTask.groovy:42)
 

### Steps to reproduce
./gradlew uploadBugsnagDynamic-sling-armeabi-releaseMapping

### Version
3.2.1

**Comment by fractalwrench** [comment]
Thanks for the report @ellsworthrw - this should be fixed in v3.2.2.
